---

- import_tasks: ntp_rhat_6-7.yml
  when: (ansible_os_family
        == "RedHat" and ansible_distribution_major_version == "6")
        or
        (ansible_os_family
        == "RedHat" and ansible_distribution_major_version == "7")

- import_tasks: ntp_rhat_8.yml
  when: (ansible_os_family
        == "RedHat" and ansible_distribution_major_version == "8")

- import_tasks: ntp_debian.yml
  when: (ansible_os_family == "Debian")
