---
- name: restart ntp
  service: name=ntp state=restarted enabled=yes

- name: restart ntpd
  service:
    name: ntpd
    state: restarted
    enabled: yes

- name: restart chronyd
  systemd:
    name: chronyd
    daemon_reload: yes
    state: restarted
    enabled: yes
